<?php

/**
 * @file
 * Contains rpgc_dndbasic.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function rpgc_dndbasic_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the rpgc_dndbasic module.
    case 'help.page.rpgc_dndbasic':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('D&amp;D Basic character creation') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function rpgc_dndbasic_theme() {
  return [
    'rpgc_dndbasic' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function rpgc_dndbasic_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'rpgc_entity_rpgc_dndbasic_add_form') {

    $rpgc_create = Drupal::service('rpgc_dndbasic.creation');
    $systemconfig = $rpgc_create->getSystemConfig();

    $pc = $rpgc_create->generatePc();

    // Name.
    $form['name']['widget'][0]['value']['#default_value'] = $pc['name'];

    // Stats.
    $defaultdice = $systemconfig['defaultdicedetails'];
    foreach ($systemconfig['statistics'] as $key => $value) {
      $form['field_' . $key]['widget'][0]['value']['#default_value'] = $pc['details']['full_stat'][$key]['sum'];
      $form['field_' . $key]['widget'][0]['value']['#description'] .= $pc['details']['full_stat'][$key]['message'];
    }

    // Alignment.
    $form['field_rpgc_dndbasic_align']['widget']['#default_value'] = $pc['alignment'];

    // Sex.
    $form['sex']['widget'][0]['value']['#default_value'] = $pc['sex'];

    // Class.
    $form['class']['widget'][0]['value']['#default_value'] = $pc['class'];

    // Class description.
    $form['class']['widget'][0]['value']['#description'] .= $pc['details']['classDescAdd'];

    // Race.
    $form['race']['widget'][0]['value']['#default_value'] = $pc['details']['class']['race'];

    // Hit points.
    $form['field_rpgc_dndbasic_hp']['widget'][0]['value']['#default_value'] = $pc['hitpoints'];
  }
}

/**
 * Compare function to sort stats by weight.
 */
function cmp($a, $b) {
  if ($a['weight'] == $b['weight']) {
    return 0;
  }
  return ($a['weight'] > $b['weight']) ? -1 : 1;
}
