<?php

/**
 * @file
 * Contains rpgc_adnd.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function rpgc_adnd_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the rpgc_adnd module.
    case 'help.page.rpgc_adnd':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Advanced D&amp;D character creation') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function rpgc_adnd_theme() {
  return [
    'rpgc_adnd' => [
      'render element' => 'children',
    ],
  ];
}
