<?php

/**
 * @file
 * Contains rpgc.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function rpgc_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the rpgc module.
    case 'help.page.rpgc':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Content entity for RPG characters') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function rpgc_theme() {
  $theme = [];
  $theme['rpgc_entity'] = [
    'render element' => 'elements',
    'file' => 'rpgc_entity.page.inc',
    'template' => 'rpgc_entity',
  ];
  $theme['rpgc_entity_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'rpgc_entity.page.inc',
  ];
  $theme[''] = [
    'render element' => 'children',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function rpgc_theme_suggestions_rpgc_entity(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#rpgc_entity'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'rpgc_entity__' . $sanitized_view_mode;
  $suggestions[] = 'rpgc_entity__' . $entity->bundle();
  $suggestions[] = 'rpgc_entity__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'rpgc_entity__' . $entity->id();
  $suggestions[] = 'rpgc_entity__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
