system:
  machine_name: dndbasic
  human_name: Dungeons & Dragons - basic

defaultdicedetails:
  dietype: 6
  numthrown: 4
  numcounted: 3
  addition: 0
  minimumhitpoints: 3

statistics:
  rpgc_dndbasic_stat_str:
    statlabel: Strength
    statabbreviation: STR
  rpgc_dndbasic_stat_int:
    statlabel: Intelligence
    statabbreviation: INT
  rpgc_dndbasic_stat_wis:
    statlabel: Wisdom
    statabbreviation: WIS
  rpgc_dndbasic_stat_dex:
    statlabel: Dexterity
    statabbreviation: DEX
  rpgc_dndbasic_stat_con:
    statlabel: Constitution
    statabbreviation: CON
  rpgc_dndbasic_stat_cha:
    statlabel: Charisma
    statabbreviation: CHA

classes:
  fighter:
    label: Fighter
    primerequisites:
      - rpgc_dndbasic_stat_str
    minimumrequirements: { }
    hitdice: 8
    minimumhitpoints: 5
    race: Human
  cleric:
    label: Cleric
    primerequisites:
      - rpgc_dndbasic_stat_str
      - rpgc_dndbasic_stat_wis
    minimumrequirements: { }
    hitdice: 6
    minimumhitpoints: 4
    race: Human
  dwarf:
    label: Dwarf
    primerequisites:
      - rpgc_dndbasic_stat_str
    minimumrequirements:
      rpgc_dndbasic_stat_con: 9
    hitdice: 8
    minimumhitpoints: 6
    race: Dwarf
  elf:
    label: Elf
    primerequisites:
      - rpgc_dndbasic_stat_str
      - rpgc_dndbasic_stat_int
    minimumrequirements:
      rpgc_dndbasic_stat_int: 9
    hitdice: 6
    minimumhitpoints: 4
    race: Elf
  halfling:
    label: Halfling
    primerequisites:
      - rpgc_dndbasic_stat_str
      - rpgc_dndbasic_stat_dex
    minimumrequirements:
      rpgc_dndbasic_stat_dex: 9
      rpgc_dndbasic_stat_con: 9
    hitdice: 6
    minimumhitpoints: 4
    race: Halfling
  magicuser:
    label: Magic-User
    primerequisites:
      - rpgc_dndbasic_stat_int
    minimumrequirements: { }
    hitdice: 4
    minimumhitpoints: 2
    race: Human
  thief:
    label: Thief
    primerequisites:
      - rpgc_dndbasic_stat_dex
    minimumrequirements: { }
    hitdice: 4
    minimumhitpoints: 3
    race: Human

alignment:
  law: Lawful
  neutral: Neutral
  chaos: Chaotic

sex:
  male: Male
  female: Female
